#!/usr/bin/env python3
"""Generate neutral JSON, portable JS and reviewed inline SVG from one asset set."""
import argparse
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
ET.register_namespace('', 'http://www.w3.org/2000/svg')
TAGS = set('svg path title stop linearGradient defs g feBlend filter feFlood feGaussianBlur polygon radialGradient circle rect feColorMatrix clipPath feOffset feComposite ellipse mask'.split())
ATTRS = set('d fill width height viewBox stop-color fill-rule offset id clip-rule x2 x1 y2 y1 gradientUnits result fill-opacity cx cy x y r in2 transform stroke stop-opacity in stroke-width filter color-interpolation-filters filterUnits flood-opacity stdDeviation gradientTransform points rx stroke-linecap values fx fy vector-effect stroke-linejoin clip-path k2 k3 operator ry maskUnits mask opacity'.split())
ALIASES = {'chatgpt':'openai', 'openai-api':'openai', 'claude-code':'claudecode', 'gemini-cli':'gemini', 'opencode':'opencode-go', 'opencodego':'opencode-go', 'kimi-k2':'kimi', 'jetbrains':'jetbrains-ai-assistant', 'xai-responses':'xai', 'grok':'xai'}
GROUPS = [('openai', 'codex'), ('anthropic', 'claude', 'claudecode'), ('copilot', 'githubcopilot')]

def inline(source):
    source = re.sub(r'<!--.*?-->', '', source, flags=re.S)
    source = re.sub(r'<\?xml [^?]*\?>', '', source)
    source = re.sub(r'<!DOCTYPE svg PUBLIC [^<>\[\]]*>', '', source)
    if '<!' in source or '<?' in source: raise ValueError('SVG declarations are not supported')
    root = ET.fromstring(source)
    for node in root.iter():
        tag = node.tag.removeprefix('{http://www.w3.org/2000/svg}')
        if tag not in TAGS: raise ValueError(f'Unsupported SVG tag {tag}')
        for attr, value in list(node.attrib.items()):
            if attr in ('style', 'role', 'aria-label', 'version', 'class'):
                del node.attrib[attr]
                continue
            if attr not in ATTRS or re.search(r'(?:https?:|data:|javascript:|[<>])', value, re.I):
                raise ValueError(f'Unsupported SVG attribute {attr}')
            if 'url(' in value and not re.fullmatch(r'url\(#[A-Za-z0-9_.-]+\)', value):
                raise ValueError('External SVG reference')
            if attr == 'id':
                if not re.fullmatch(r'[A-Za-z0-9_.-]+', value): raise ValueError('Invalid SVG id')
                node.set(attr, '__AD_ICON__' + value)
            elif 'url(#' in value: node.set(attr, value.replace('url(#', 'url(#__AD_ICON__'))
        for child in list(node):
            if child.tag.endswith('}title'): node.remove(child)
    root.set('aria-hidden', 'true')
    root.set('focusable', 'false')
    return ET.tostring(root, encoding='unicode')

def outputs():
    icons, svgs = {}, {}
    for file in sorted((ROOT/'assets').glob('*.svg')):
        source = file.read_text()
        svgs[file.name] = inline(source)
        if file.stem.endswith('-color'): continue
        title = ET.fromstring(source).find('{http://www.w3.org/2000/svg}title')
        name = title.text if title is not None else file.stem.replace('-', ' ').title()
        if file.stem == 'openai': name = 'ChatGPT / OpenAI'
        entry = {'name': name, 'monochrome':file.name, 'alternatives':[file.stem]}
        if (ROOT/'assets'/f'{file.stem}-color.svg').exists(): entry['color'] = f'{file.stem}-color.svg'
        icons[file.stem] = entry
    for group in GROUPS:
        for key in group: icons[key]['alternatives'] = list(group)
    assert all(value in icons for value in ALIASES.values())
    manifest = {'version':1, 'icons':icons, 'aliases':ALIASES}
    return {
        'manifest.json':json.dumps(manifest, indent=2)+'\n',
        'manifest.js':'// Generated by scripts/build.py. Do not edit.\nexport const catalog = '+json.dumps(manifest, separators=(',',':'))+';\n',
        'svg.js':"// Generated by scripts/build.py. Do not edit.\nimport {resolveProviderIcon} from './index.js';\nconst svg = "+json.dumps(svgs,separators=(',',':'))+";\nexport function providerIconSvg(provider, options = {}) {\n    const icon = resolveProviderIcon(provider, options);\n    const prefix = options.prefix ?? 'ad-icon';\n    if (!icon || !/^[A-Za-z][A-Za-z0-9_-]{0,100}$/.test(prefix)) return undefined;\n    return svg[icon.file].replaceAll('__AD_ICON__', prefix + '-');\n}\n"
    }

if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    for name,content in outputs().items():
        path=ROOT/name
        if args.check:
            assert path.read_text() == content, f'{name} is out of date; run npm run build'
        else: path.write_text(content)
